stages:
  - prebuild
  - cross_build

.cross_build_job_template: &cross_build_job_definition
  stage: cross_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN)

# There are many possible cross-arch jobs we could do, but to preserve
# limited CI resource time allocated to users, we cut it down to two
# interesting variants. The default jobs are x86_64, which means 64-bit
# and little endian. We thus pick armv7l as an interesting 32-bit
# platform, and s390x as an interesting big endian platform. We split
# between Debian 10 and sid to help detect problems on the horizon.

s390x-debian-10:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-s390x:latest

armv7l-debian-sid:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-armv7l:latest

mingw32-fedora-30:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw32:latest

mingw64-fedora-30:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw64:latest

# This artifact published by this job is downloaded by libvirt.org to
# be deployed to the web root:
#    https://gitlab.com/libvirt/libvirt/-/jobs/artifacts/master/download?job=website
website:
  stage: prebuild
  script:
    - mkdir build
    - cd build
    - ../autogen.sh --prefix=$(pwd)/../vroot || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN) -C docs
    - make -j $(getconf _NPROCESSORS_ONLN) -C docs install
    - cd ..
    - mv vroot/share/doc/libvirt/html/ website
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest
  artifacts:
    expose_as: 'Website'
    name: 'website'
    when: on_success
    expire_in: 30 days
    paths:
      - website
