stages:
  - website
  - native_build
  - cross_build


.native_build_job_template: &native_build_job_definition
  stage: native_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN) syntax-check
    - make -j $(getconf _NPROCESSORS_ONLN) distcheck

debian-9:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9:latest

centos-7:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-centos-7:latest

fedora-31:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest

fedora-rawhide:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-rawhide:latest

ubuntu-1804:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-ubuntu-1804:latest


.cross_build_job_template: &cross_build_job_definition
  stage: cross_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN)


# There are many possible cross-arch jobs we could do, but to preserve
# limited CI resource time allocated to users, we cut it down to two
# interesting variants. The default jobs are x86_64, which means 64-bit
# and little endian. We thus pick armv7l as an interesting 32-bit
# platform, and s390x as an interesting big endian platform. We split
# between Debian 10 and sid to help detect problems on the horizon.

s390x-cross-debian-10:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-s390x:latest

armv7l-cross-debian-sid:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-armv7l:latest

mingw32-cross-fedora-30:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw32:latest

mingw64-cross-fedora-30:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw64:latest

# This artifact published by this job is downloaded by libvirt.org to
# be deployed to the web root:
#    https://gitlab.com/libvirt/libvirt/-/jobs/artifacts/master/download?job=website
website:
  stage: website
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS --prefix=$(pwd)/../vroot || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN)
    - make -j $(getconf _NPROCESSORS_ONLN) install
    - cd ..
    - mv vroot/share/doc/libvirt/html/ website
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest
  variables:
    CONFIGURE_OPTS: --without-libvirtd --without-esx --without-hyperv --without-test --without-dtrace --without-openvz --without-vmware --without-attr --without-audit --without-blkid --without-bash-completion --without-capng --without-curl --without-dbus --without-firewalld --without-fuse --without-glusterfs --without-libiscsi --without-libssh --without-numactl --without-openwsman --without-pciaccess --without-readline --without-sanlock  --without-sasl --without-selinux --without-ssh2  --without-udev
  artifacts:
    expose_as: 'Website'
    name: 'website'
    when: on_success
    expire_in: 30 days
    paths:
      - website
