variables:
  MAKE: make
  GIT_DEPTH: 100

stages:
  - cross_build


.cross_build_default_job_template: &cross_build_default_job_definition
  stage: cross_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - $MAKE -j $(getconf _NPROCESSORS_ONLN)

# We could run every arch on every versions, but it is a little
# overkill. Instead we split jobs evenly across 9, 10 and sid
# to achieve reasonable cross-coverage.

debian-9-cross-armv6l:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9-cross-armv6l:latest

debian-9-cross-mips64el:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9-cross-mips64el:latest

debian-9-cross-mips:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9-cross-mips:latest

debian-10-cross-aarch64:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-aarch64:latest

debian-10-cross-ppc64le:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-ppc64le:latest

debian-10-cross-s390x:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-s390x:latest

debian-sid-cross-armv7l:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-armv7l:latest

debian-sid-cross-i686:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-i686:latest

debian-sid-cross-mipsel:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-mipsel:latest
