stages:
  - prebuild
  - native_build
  - cross_build
  - native_build_extra


# Common templates

# Native jobs that run every time, pre/post merge and on any branch
.native_build_job_template: &native_build_job_definition
  stage: native_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN) syntax-check
    - make -j $(getconf _NPROCESSORS_ONLN) distcheck

# Native jobs that will only run post merge on master branch
# Switch to running against merge requests later
.native_build_extra_job_template: &native_build_extra_job_definition
  stage: native_build_extra
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - $MAKE -j $(getconf _NPROCESSORS_ONLN) check
  only:
    refs:
     - master

.cross_build_job_template: &cross_build_job_definition
  stage: cross_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN)


# Native architecture build + test jobs

x64-debian-9:
  <<: *native_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9:latest

x64-debian-10:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10:latest

x64-debian-sid:
  <<: *native_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid:latest

x64-centos-7:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-centos-7:latest

x64-centos-8:
  <<: *native_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-centos-8:latest

x64-fedora-30:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30:latest

x64-fedora-31:
  <<: *native_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest

x64-fedora-rawhide:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-rawhide:latest

x64-opensuse-151:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-opensuse-151:latest

x64-ubuntu-1604:
  <<: *native_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-ubuntu-1604:latest

x64-ubuntu-1804:
  <<: *native_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-ubuntu-1804:latest


# Cross compiled build jobs

# There are many possible cross-arch jobs we could do, but to preserve
# limited CI resource time allocated to users, we cut it down to two
# interesting variants. The default jobs are x86_64, which means 64-bit
# and little endian. We thus pick armv7l as an interesting 32-bit
# platform, and s390x as an interesting big endian platform. We split
# between Debian 10 and sid to help detect problems on the horizon.

s390x-debian-10:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-s390x:latest

armv7l-debian-sid:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-armv7l:latest

mingw32-fedora-30:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw32:latest

mingw64-fedora-30:
  <<: *cross_build_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw64:latest

# This artifact published by this job is downloaded by libvirt.org to
# be deployed to the web root:
#    https://gitlab.com/libvirt/libvirt/-/jobs/artifacts/master/download?job=website
website:
  stage: prebuild
  script:
    - mkdir build
    - cd build
    - ../autogen.sh --prefix=$(pwd)/../vroot || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN) -C docs
    - make -j $(getconf _NPROCESSORS_ONLN) -C docs install
    - cd ..
    - mv vroot/share/doc/libvirt/html/ website
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest
  artifacts:
    expose_as: 'Website'
    name: 'website'
    when: on_success
    expire_in: 30 days
    paths:
      - website
