.job_template: &job_definition
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - make -j $(getconf _NPROCESSORS_ONLN)

# We could run every arch on both versions, but it is a little
# overkill. Instead we split jobs evenly across 9, 10 and sid
# to achieve reasonable cross-coverage.

debian-9-cross-armv6l:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-9-cross-armv6l:master

debian-9-cross-mipsel:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-9-cross-mipsel:master

debian-9-cross-ppc64le:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-9-cross-ppc64le:master

debian-10-cross-s390x:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-10-cross-s390x:master

debian-10-cross-i686:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-10-cross-i686:master

debian-10-cross-aarch64:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-10-cross-aarch64:master

debian-sid-cross-armv7l:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-sid-cross-armv7l:master

debian-sid-cross-mips64el:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-sid-cross-mips64el:master

debian-sid-cross-mips:
  <<: *job_definition
  image: quay.io/libvirt/buildenv-debian-sid-cross-mips:master
