#!/bin/sh
# run virsh self-test to make sure command option structures are valid

# Copyright (C) 2016 Red Hat, Inc.

# SPDX-License-Identifier: GPL-2.0-or-later

. "$(dirname $0)/test-lib.sh"

fail=0

basename=$(basename $0)

if test "x$basename" = "xvirsh-self-test" ; then
    binary=virsh
    extra_args="-c test:///default"
elif test "x$basename" = "xvirt-admin-self-test" ; then
    binary=virt-admin
    extra_args=""
else
    echo "Unknown binary: $basename";
    exit 1
fi

test_intro "$0"
$abs_top_builddir/tools/${binary} ${extra_args} self-test > /dev/null
status=$?
test_result 1 "$0" ${status}

if test "${status}" != "0" ; then
   fail=1
fi

test_final $counter $fail

(exit $fail); exit $fail
