#!/bin/sh
# exercise virsh's "undefine" command

# Copyright (C) 2008-2009, 2011 Red Hat, Inc.

# SPDX-License-Identifier: GPL-2.0-or-later

. "$(dirname $0)/test-lib.sh"

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

fail=0

# Attempt to undefine a running domain, by domain name.  Every time a new
# connection is opened to the test driver, it starts life with a new
# persistent running domain named 'test' with a different uuid, so
# testing this command requires batch mode use of virsh.
$abs_top_builddir/tools/virsh -c test:///default \
    'dominfo test; undefine test; dominfo test' > out1 2>&1
test $? = 0 || fail=1
sed '/^Persistent/n; /:/d' < out1 > out
cat <<\EOF > exp || fail=1
Persistent:     yes

Domain test has been undefined

Persistent:     no

EOF
compare exp out || fail=1

# A similar diagnostic when specifying a domain ID
$abs_top_builddir/tools/virsh -c test:///default \
    'dominfo 1; undefine 1; dominfo 1' > out1 2>&1
test $? = 0 || fail=1
sed '/^Persistent/n; /:/d' < out1 > out
cat <<\EOF > exp || fail=1
Persistent:     yes

Domain 1 has been undefined

Persistent:     no

EOF
compare exp out || fail=1

# Succeed, now: first shut down, then undefine, both via name.
$abs_top_builddir/tools/virsh -c test:///default \
    'shutdown test; undefine test; dominfo test' > out 2>&1
test $? = 1 || fail=1
cat <<\EOF > expout || fail=1
Domain test is being shutdown

Domain test has been undefined

error: failed to get domain 'test'

EOF
compare expout out || fail=1

(exit $fail); exit $fail
