#!/bin/sh
# ensure that defining with an invalid vCPU cpuset elicits a diagnostic

# Copyright (C) 2008-2009 Red Hat, Inc.

# SPDX-License-Identifier: GPL-2.0-or-later

. "$(dirname $0)/test-lib.sh"

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

fail=0

# generate input
$abs_top_builddir/tools/virsh --connect test:///default dumpxml 1 > xml || fail=1

# require the presence of the string we'll transform
grep '<vcpu placement' xml > /dev/null || fail=1

sed "s/vcpu placement='static'>/vcpu cpuset='aaa'>/" xml > xml-invalid || fail=1

# Require failure and a diagnostic.
$abs_top_builddir/tools/virsh --connect test:///default define xml-invalid > out 2>&1 && fail=1
cat <<\EOF > exp || fail=1
error: Failed to define domain from xml-invalid
error: invalid argument: Failed to parse bitmap 'aaa'

EOF
compare exp out || fail=1

(exit $fail); exit $fail
