#!/bin/sh
# ensure that virsh start works properly

# Copyright (C) 2008 Red Hat, Inc.

# SPDX-License-Identifier: GPL-2.0-or-later

. "$(dirname $0)/test-lib.sh"

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

fail=0

test_url=test:///default

# expect this to fail
$abs_top_builddir/tools/virsh -c $test_url start test > out 2> err && fail=1

# stdout gets a newline
echo > exp || fail=1
compare exp out || fail=1

echo 'error: Domain is already active' > exp || fail=1
compare exp err || fail=1

(exit $fail); exit $fail
