#!/bin/sh
# ensure that certain file-reading commands can handle non-seekable files

# Copyright (C) 2008 Red Hat, Inc.

# SPDX-License-Identifier: GPL-2.0-or-later

. "$(dirname $0)/test-lib.sh"

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

fail=0

cat <<\EOF > dom
<domain type='test' id='2'>
  <name>t2</name>
  <uuid>004b96e1-2d78-c30f-5aa5-000000000000</uuid>
  <memory>8388608</memory>
  <vcpu>2</vcpu>
  <os>
    <type>xen</type>
  </os>
  <on_reboot>restart</on_reboot>
  <on_poweroff>destroy</on_poweroff>
  <on_crash>restart</on_crash>
</domain>
EOF

$abs_top_builddir/tools/virsh -c test:///default define dom > /dev/null || fail=1

mkfifo_or_skip_ fifo
cat dom > fifo &

$abs_top_builddir/tools/virsh -c test:///default define fifo > /dev/null || fail=1

(exit $fail); exit $fail
