#!/bin/sh
# exercise virsh's "domrename" command

# Copyright (C) 2008-2009, 2017 Red Hat, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHEXP ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

. "$(dirname $0)/test-lib.sh"

if test "$VERBOSE" = yes; then
  set -x
  $abs_top_builddir/tools/virsh --version
fi

fail=0

# Succeed, now: first shut down, then rename the domain.
$abs_top_builddir/tools/virsh -q -c test:///default \
    'shutdown test; domrename test anothertest' > out 2>&1
test $? = 1 && fail=1

# Failed, now: rename the domain without shutting down.
$abs_top_builddir/tools/virsh -q -c test:///default \
    'domrename test anothertest' > out 2>&1
test $? = 1 || fail=1
cat <<\EOF > expout || fail=1
error: Requested operation is not valid: cannot rename active domain
EOF
compare expout out || fail=1

(exit $fail); exit $fail
