#!/bin/sh
# Ensure that virsh schedinfo --set invalid=val fails

# Copyright (C) 2010-2011, 2013 Red Hat, Inc.

# SPDX-License-Identifier: GPL-2.0-or-later

. "$(dirname $0)/test-lib.sh"

VIRSH=$abs_top_builddir/tools/virsh

if test "$VERBOSE" = yes; then
  set -x
  $VIRSH --version
fi

printf 'Scheduler      : fair\n\n' > exp-out || framework_failure
printf 'error: invalid scheduler option: j\n' > exp-err || framework_failure

fail=0

test_url=test:///default

$VIRSH -c $test_url schedinfo 1 --set j=k >out 2>err && fail=1
compare exp-out out || fail=1
compare exp-err err || fail=1

(exit $fail); exit $fail
