---
- name: '{{ project }}: Load variables'
  include_vars:
    file: 'vars/{{ project }}/{{ os_name }}-{{ os_version }}.yml'

- name: '{{ project }}: Drop local changes'
  command: git reset --hard
  args:
    chdir: '{{ project }}'

- name: '{{ project }}: Clean up'
  command: git clean -xdf
  args:
    chdir: '{{ project }}'

# C build

- name: '{{ project }}: Prepare configure options'
  set_fact:
    configure_options: []

- name: '{{ project }}: Prepare configure options'
  set_fact:
    configure_options: '{{ configure_options }} + [ "{{ features[item] }}" ]'
  with_items:
    '{{ features }}'
  when:
    - features is defined

- name: '{{ project }}: Prepare configure options'
  set_fact:
    configure_options: '{{ configure_options | join(" ") }}'

- name: '{{ project }}: Run autogen.sh'
  command: './autogen.sh {{ configure_options }}'
  args:
    chdir: '{{ project }}'
  environment:
  when:
    - ( project == 'libosinfo' or
        project == 'libvirt' or
        project == 'libvirt-cim' or
        project == 'libvirt-glib' )

- name: '{{ project }}: Run configure'
  command: './configure {{ configure_options }}'
  args:
    chdir: '{{ project }}'
  when:
   - project == 'libvirt-cim'

- name: '{{ project }}: Build project'
  command: '{{ make }} -j{{ smp }}'
  args:
    chdir: '{{ project }}'
  when:
    - ( project == 'libosinfo' or
        project == 'libvirt' or
        project == 'libvirt-cim' or
        project == 'libvirt-glib' )

- name: '{{ project }}: Run sanity checks'
  command: '{{ make }} -j{{ smp }} syntax-check'
  args:
    chdir: '{{ project }}'
  when:
    - ( project == 'libosinfo' or
        ( project == 'libvirt' and
          os_name != 'FreeBSD' ) or
        project == 'libvirt-glib' )

- name: '{{ project }}: Run test suite'
  command: '{{ make }} -j{{ smp }} check'
  args:
    chdir: '{{ project }}'
  when:
    - ( ( project == 'libvirt' and
          os_name != 'FreeBSD' ) or
        project == 'libvirt-cim' or
        project == 'libvirt-glib' )

- name: '{{ project }}: Build RPM package'
  command: '{{ make }} -j{{ smp }} rpm'
  args:
    chdir: '{{ project }}'
  when:
    - ( os_name == 'CentOS' or
        os_name == 'Fedora' )
    - ( project == 'libvirt' or
        project == 'libvirt-cim' )

# Go build

- name: '{{ project }}: Build project'
  command: go build -v
  args:
    chdir: '{{ project }}'
  when:
    - ( project == 'libvirt-go' or
        project == 'libvirt-go-xml' )

- name: '{{ project }}: Run test suite'
  command: go test -tags api
  args:
    chdir: '{{ project }}'
  when:
    - ( project == 'libvirt-go' or
        project == 'libvirt-go-xml' )

# Perl build (makemaker)

- name: '{{ project }}: Run Makefile.PL'
  command: perl Makefile.PL
  args:
    chdir: '{{ project }}'
  when:
    - project == 'libvirt-perl'
    - false

- name: '{{ project }}: Build project'
  command: '{{ make }}'
  args:
    chdir: '{{ project }}'
  when:
    - project == 'libvirt-perl'
    - false

- name: '{{ project }}: Build project manifest'
  command: '{{ make }} -j{{ smp }} manifest'
  args:
    chdir: '{{ project }}'
  when:
    - project == 'libvirt-perl'
    - false

- name: '{{ project }}: Run test suite'
  command: '{{ make }} -j{{ smp }} test'
  args:
    chdir: '{{ project }}'
  when:
    - project == 'libvirt-perl'
    - false
