---
- name: Create compatibility symlinks
  file:
    src: '/usr/local/{{ item }}'
    dest: '/usr/{{ item }}'
    state: link
    force: yes
  with_items:
    - include/readline
    - include/sasl
    - include/yajl
    - lib/libreadline.so
    - lib/libsasl2.so
    - lib/libyajl.so
  when:
    - os_name == 'FreeBSD'
