---
- name: Set additional facts
  set_fact:
    os_name: '{{ ansible_distribution }}'
    os_version: '{{ ansible_distribution_major_version }}'
  when:
    - ansible_distribution_release != 'Rawhide'

- name: Set additional facts
  set_fact:
    os_name: '{{ ansible_distribution }}'
    os_version: Rawhide
  when:
    - ansible_distribution_release == 'Rawhide'
