---
- name: '{{ project }}: Load variables'
  include_vars:
    file: 'vars/{{ project }}/{{ os_name }}-{{ os_version }}.yml'

- name: '{{ project }}: Install packages'
  package:
    name: '{{ item }}'
    state: present
  with_items:
    '{{ packages }}'

- name: '{{ project }}: Install extra packages'
  package:
    name: '{{ item }}'
    state: present
  with_items:
    '{{ extra_packages }}'
  when:
    - extra_packages is defined
    # Only extra additional packages if we're going to build later on
    - build
