---
- hosts: all

  tasks:

    # Prepare the base environment
    - include: tasks/facts.yml
    - include: tasks/base.yml
    - include: tasks/compat.yml

    # Install build dependencies for each project
    - include: tasks/packages.yml
      with_items:
        '{{ projects }}'
      loop_control:
        loop_var: project
      when:
        - projects is defined

    - include: tasks/build.yml
      with_items:
        '{{ projects }}'
      loop_control:
        loop_var: project
      when:
        - projects is defined
        # base is a pseudo-projects
        - project != 'base'
        # Building can be turned on and off
        - build
