---
- hosts: all

  tasks:

    # Prepare the base environment
    - include: tasks/facts.yml
    - include: tasks/base.yml
    - include: tasks/compat.yml

    # Install build dependencies for each project
    - include: tasks/packages.yml
      with_items:
        '{{ projects }}'
      loop_control:
        loop_var: project
      when:
        - projects is defined

    # Configure the Jenkins agent
    - include: tasks/jenkins.yml
      when:
        - projects is defined
        # jenkins is a pseudo-project
        - ( 'jenkins' in projects )

    - include: tasks/build.yml
      with_items:
        '{{ projects }}'
      loop_control:
        loop_var: project
      when:
        - projects is defined
        # base and jenkins are pseudo-projects
        - project != 'base'
        - project != 'jenkins'
        # Building can be turned on and off
        - build
